labelRegion = {
    "SR_ee": "Signal Region",
    "CR_Zee_bjets": "Z+bjets Region",
    "CR_Zee_lightjets": "Z+lightjets Region",
    "CR_ee_ttbar": "t#bar{t} Region",
    "SR_mm": "Signal Region",
    "CR_Zmm_bjets": "Z+bjets Region",
    "CR_Zmm_lightjets": "Z+lightjets Region",
    "CR_mm_ttbar": "t#bar{t} Region",
}
labelLeptons = {
    "SR_ee": "Electrons",
    "CR_Zee_bjets": "Electrons",
    "CR_Zee_lightjets": "Electrons",
    "CR_ee_ttbar": "Electrons",
    "SR_mm": "Muons",
    "CR_Zmm_bjets": "Muons",
    "CR_Zmm_lightjets": "Muons",
    "CR_mm_ttbar": "Muons",
}
labelBtag = {
    "deepflav": "",
    "deepcsv": "",
}

labelVariable = {
    "Zee_mass": "m_{ee} (GeV)",
    "Zmm_mass": "m_{#mu#mu} (GeV)",
    "Z_mass": "m_{Z} (GeV)",
    "Zee_pt": "p_{T}(ee) (GeV)",
    "Zmm_pt": "p_{T}(#mu#mu) (GeV)",
    "Z_pt": "p_{T}(Z) (GeV)",
    "Dijets_mass": "m_{jj} (GeV)",
    "Dijets_pt": "p_{T}(jj) (GeV)",
    "MET_pt": "p_{T}^{miss} (GeV)",
    "ZH_dphi": "#Delta#phi(Z,jj)",
    "ZH_deta": "#Delta#eta(Z,jj)",
    "ZH_dr": "#DeltaR(Z,jj)",
    "HZ_ptRatio": "p_{T}(jj)/p_{T}(Z)",
    "btag_max": "btag_{max}",
    "btag_min": "btag_{min}",
    "hadronFlavour_btag_max": "btag_{max}^{HF}",
    "hadronFlavour_btag_min": "btag_{min}^{HF}",
    "LHE_Nb": "N_{b}^{LHE}",
    "jj_dphi": "#Delta#phi(jj)",
    "jj_deta": "#Delta#eta(jj)",
    "jj_dr": "#DeltaR(jj)",
    "JetBtagMax_pt": "p_{T}^{max} (GeV)",
    "JetBtagMin_pt": "p_{T}^{min} (GeV)",
    "SoftActivityJetNjets5": "N_{jets}^{soft} (p_{T} > 5 GeV)",
    "atanhDNN_Score": "atanh(DNN Score)",
}

labelLegend = {
    "ZH": "ZH(b#bar{b})",
    "ggZH": "ggZH(b#bar{b})",
    "TT": "t#bar{t}",
    "ST": "Single top",
    "Z+udsg": "Z+udsg",
    "Z+b": "Z+b",
    "Z+bb": "Z+b#bar{b}",
    "Z+c": "Z+c",
    "VVHF": "VVHF",
    "VVLF": "VVLF",
    "bkg_0b": "bkg_{0b}",
    "bkg_1b": "bkg_{1b}",
    "bkg_2b": "bkg_{2b}",
    "FullSim": "FullSim",
    "FlashSim": "FlashSim",
    "Oversampling": "FlashSim (#times 10000)",
    "DYZpt-0To50": "p_{T}^{Z} < 50 GeV",
    "DYZpt-50To100": "50 < p_{T}^{Z} < 100 GeV",
    "DYZpt-100To250": "100 < p_{T}^{Z} < 250 GeV",
    "DYZpt-250To400": "250 < p_{T}^{Z} < 400 GeV",
    "DYZpt-400To650": "400 < p_{T}^{Z} < 650 GeV",
    "DYZpt-650ToInf": "p_{T}^{Z} > 650 GeV",
    "DY-Zpt-100To250": "100 < p_{T} < 250 GeV",
}

labelStatUncRange = {
    "Z_pt": (-0.05, 0.5),
    "Z_mass": (-0.1, 0.15),
    "JetBtagMax_pt": (-0.05, 0.45),
    "JetBtagMin_pt": (-0.05, 0.45),
    "Dijets_mass": (-0, 0.1),
    "HZ_ptRatio": (-0.01, 0.3),
    "Dijets_pt": (-0.05, 0.25),
}
