labelRegion = {
    "SR_ee": "Signal Region",
    "CR_Zee_bjets": "Z+bjets Region",
    "CR_Zee_lightjets": "Z+lightjets Region",
    "CR_ee_ttbar": "t#bar{t} Region",
    "SR_mm": "Signal Region",
    "CR_Zmm_bjets": "Z+bjets Region",
    "CR_Zmm_lightjets": "Z+lightjets Region",
    "CR_mm_ttbar": "t#bar{t} Region",
}
labelLeptons = {
    "SR_ee": "Electrons",
    "CR_Zee_bjets": "Electrons",
    "CR_Zee_lightjets": "Electrons",
    "CR_ee_ttbar": "Electrons",
    "SR_mm": "Muons",
    "CR_Zmm_bjets": "Muons",
    "CR_Zmm_lightjets": "Muons",
    "CR_mm_ttbar": "Muons",
}
labelBtag = {
    "deepflav": "",
    "deepcsv": "",
}

labelVariable = {
    "Zee_mass": "m_{ee}",
    "Zmm_mass": "m_{#mu#mu}",
    "Z_mass": "m_{Z}",
    "Zee_pt": "p_{T}(ee)",
    "Zmm_pt": "p_{T}(#mu#mu)",
    "Z_pt": "p_{T}(Z)",
    "Dijets_mass": "m_{jj}",
    "Dijets_pt": "p_{T}(jj)",
    "MET_pt": "p_{T}^{miss}",
    "ZH_dphi": "#Delta#phi(Z,jj)",
    "ZH_deta": "#Delta#eta(Z,jj)",
    "ZH_dr": "#DeltaR(Z,jj)",
    "HZ_ptRatio": "p_{T}(jj)/p_{T}(Z)",
    "btag_max": "btag_{max}",
    "btag_min": "btag_{min}",
    "hadronFlavour_btag_max": "btag_{max}^{HF}",
    "hadronFlavour_btag_min": "btag_{min}^{HF}",
    "LHE_Nb": "N_{b}^{LHE}",
    "jj_dphi": "#Delta#phi(jj)",
    "jj_deta": "#Delta#eta(jj)",
    "jj_dr": "#DeltaR(jj)",
    "JetBtagMax_pt": "p_{T}^{max}",
    "JetBtagMin_pt": "p_{T}^{min}",
    "SoftActivityJetNjets5": "N_{jets}^{soft} (p_{T} > 5 GeV)",
    "atanhDNN_Score": "atanh(DNN Score)",
}

labelLegend = {
    "ZH": "ZH(b#bar{b})",
    "ggZH": "ggZH(b#bar{b})",
    "TT": "t#bar{t}",
    "ST": "Single top",
    "Z+udsg": "Z+udsg",
    "Z+b": "Z+b",
    "Z+bb": "Z+b#bar{b}",
    "Z+c": "Z+c",
    "VVHF": "VVHF",
    "VVLF": "VVLF",
    "bkg_0b": "bkg_{0b}",
    "bkg_1b": "bkg_{1b}",
    "bkg_2b": "bkg_{2b}",
    "FullSim": "FullSim",
    "FlashSim": "FlashSim",
}
